---
- name: Setup Nginx with Docker/Podman
  hosts: all
  gather_facts: yes
  vars_files:
    - index.yaml
    - certs.yaml

  become: yes

  tasks:
    - name: Create deployment directory
      file:
        path: /home/xlab/docker
        state: directory
        owner: xlab
        group: xlab
        mode: '0755'

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: xlab
        group: xlab
        mode: '0775'
      loop:
        - /home/xlab/docker/html
        - /home/xlab/docker/certs
        - /home/xlab/docker/conf.d

    - name: Create index.html file
      copy:
        dest: /home/xlab/docker/html/index.html
        content: "{{ index_html }}"
        owner: xlab
        group: xlab
        mode: '0644'

    - name: Generate SSL certificates (self-signed for testing)
      command: >
        openssl req -x509 -newkey rsa:4096
        -keyout {{ ssl_key_path }}
        -out {{ ssl_cert_path }}
        -days {{ days_valid }} -nodes
        -subj "/C={{ country }}/ST={{ state }}/L={{ locality }}/O={{ organization }}/CN={{ common_name }}"
      args:
        creates: "{{ ssl_cert_path }}"

    - name: Copy default .conf to the nginx server
      copy:
        src: ../default.conf
        dest: /home/xlab/docker/conf.d/default.conf
        owner: xlab
        group: xlab
        mode: '0644'

    # Install Docker on Ubuntu (for non-RedHat systems)
    - name: Update package lists (Debian)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install required packages (Debian)
      apt:
        name:
          - ca-certificates
          - curl
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker packages (Ubuntu)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Generate docker-compose.yml
      template:
        src: ../docker-compose.yml
        dest: /home/xlab/docker/docker-compose.yml
        owner: xlab
        group: xlab
        mode: '0644'
      when: ansible_distribution == "Ubuntu"

    - name: Run Docker Compose (Ubuntu)
      command: docker compose up -d
      args:
        chdir: /home/xlab/docker
      when: ansible_distribution == "Ubuntu"

    - name: Set correct SELinux context for nginx html directory
      command: chcon -R -t httpd_sys_content_t /home/xlab/docker/html
      when: ansible_distribution_file_variety == "RedHat"

    - name: Install Podman and dependencies (RedHat)
      dnf:
        name:
          - python3-pip
          - podman
        state: latest
      when: ansible_distribution_file_variety == "RedHat"

    - name: Enable podman.socket and podman service to start on boot (RedHat)
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - podman.socket
        - podman
      when: ansible_distribution_file_variety == "RedHat"

    - name: Create Podman container for Nginx (HTTP + HTTPS)
      containers.podman.podman_container:
        name: nginx_test
        image: docker.io/library/nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "/home/xlab/docker/html:/usr/share/nginx/html:Z"
          - "/home/xlab/docker/certs:/etc/nginx/certs:Z"
          - "/home/xlab/docker/conf.d:/etc/nginx/conf.d:Z"
      when: ansible_distribution_file_variety == "RedHat"

    - name: Create custom systemd service for nginx_test container (RedHat)
      copy:
        dest: /etc/systemd/system/container-nginx_test.service
        content: |
          [Unit]
          Description=Podman container for nginx_test
          After=network.target

          [Service]
          ExecStart=/usr/bin/podman start -a nginx_test
          ExecStop=/usr/bin/podman stop -t 10 nginx_test
          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
      when: ansible_distribution_file_variety == "RedHat"

    - name: Reload systemd daemon (RedHat)
      systemd:
        daemon_reload: yes
      when: ansible_distribution_file_variety == "RedHat"

    - name: Enable and start nginx_test service (RedHat)
      systemd:
        name: container-nginx_test.service
        enabled: yes
        state: started
      when: ansible_distribution_file_variety == "RedHat"

    - name: Check if the index.html file is in the container
      command: podman exec nginx_test ls -l /usr/share/nginx/html/index.html
      register: index_check
      ignore_errors: yes
      when: ansible_distribution_file_variety == "RedHat"

    - name: Debug index.html mount
      debug:
        var: index_check
